version: '3'

services: 
    django_app:
        build: 
            context: .
            dockerfile: Dockerfile
        ports: 
            - '8000:8000'
        volumes: 
            - ./REST-foundation:/REST-FOUND
        command: "python manage.py runserver 0.0.0.0:8000"